# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "LetterLiGO"
repo_name: "letterli-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 100

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/letterli-arxiv-daily.json'
json_gitpage_path: './docs/letterli-arxiv-daily-web.json'
json_wechat_path: './docs/letterli-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Text-to-Image Safety": 
        filters: ["Text-to-Image Safety", "Diffusion Safety", "Jailbreak Text-to-Image"]
    "LLM Security & Privacy": 
        filters: ["LLM Security", "LLM Privacy"]
    "LLM Agent Security & Privacy":
        filters: ["LLM Agent Security", "LLM Agent Privacy", "Prompt Injection Attack"]
    "Celluar Network Security":
        filters: ["LLM for 5G Security", "LLM for celluar network security"]
    "Audio Deepfake":
        filters: ["Audio Deepfake Detection"]
    "Embodied AI Security & Privacy":
        filters: ["Embodied AI Security", "Embodied AI Privacy"]
