title: LetterLi Arxiv Daily
description: Automatically Update Security Papers Daily using Github Actions (Update Every 8th hours)
show_downloads: true

github:
  zip_url: https://github.com/LetterLiGO/letterli-arxiv-daily
  another_url: https://github.com/LetterLiGO/letterli-arxiv-daily

## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark
social_links:
  twitter: AlphaRealcat
  github: LetterLiGO

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag
